version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  allow:
  - dependency-type: direct
  ignore:
  - dependency-name: reqwest
    versions:
    - 0.11.0
    - 0.11.1
    - 0.11.2
